controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    node_1_controller:
      type: canopen_ros2_controllers/CanopenProxyController

node_1_controller:
  ros__parameters:
    joint: node_1
